#' plot_rankmaps function
#'
#' This function enables access to priority rank maps generated by Zonation.
#'
#' @param variants Indices of setups to plot.
#' @param main_directory Main directory containing setup subdirectories.
#' @param cols Number of columns for arranging plots.
#'
#' @details This function relies on two external packages: `cptcity` and 
#' `terra`. Additionally, it assumes a specific folder structure with setup 
#' subdirectories prefixed with "setup_".
#'
#' @importFrom cptcity cpt
#' @importFrom terra rast
#'
#' @examples
#' # Plot rank maps for setups 1 to 6 in 3 columns
#' plot_rankmaps(variants = 1:6, cols = 3)
#'
#' @export
#'
plot_rankmaps <- function(variants, main_directory = ".", cols = 2) {
  # Get a list of all subdirectories with "setup_" in their names
  setup_folders <- list.files(path = main_directory, pattern = "^setup_.*", 
                              full.names = TRUE)
  
  # Filter setup folders based on selected indices
  selected_setups <- setup_folders[variants]
  
  # Initialize an empty list to store the file paths and IDs
  rankmap_files <- list()
  
  # Loop through selected setup folders and find rankmap.tif files within the output folder
  for (i in seq_along(selected_setups)) {
    setup_folder <- selected_setups[i]
    output_folder <- file.path(setup_folder, "output")
    rankmap_path <- file.path(output_folder, "rankmap.tif")
    
    # Check if the rankmap.tif file exists, and if yes, add its path and ID to the list
    if (file.exists(rankmap_path)) {
      rankmap_files[[i]] <- list(path = rankmap_path, id = i)
    } else {
      message(paste("Warning: Missing rankmap.tif file in Setup", variants[i], "- Skipping this setup."))
    }
  }
  
  # Load the list of rankmap.tif files as raster objects along with their IDs
  rankmap_rasters <- lapply(rankmap_files, function(file) {
    list(id = file$id, raster = rast(file$path))
  })
  
  # Calculate the number of columns based on the number of plots
  num_plots <- length(rankmap_rasters)
  cols <- ifelse(num_plots <= 2, num_plots, 2)  # You can adjust this condition as needed
  
  # Calculate appropriate margin values for the plots
  margin_height <- 0.5  # Adjust this value as needed
  margin_width <- 0.5   # Adjust this value as needed
  
  # Calculate rows and cols for the layout
  rows <- ceiling(num_plots / cols)
  
  # Calculate the total width and height of the plots
  total_width <- cols + cols * margin_width
  total_height <- rows + rows * margin_height
  
  # Set up the plotting layout with adjusted margins
  par(mfrow = c(rows, cols), mar = c(3, 3, margin_height, margin_width))
  
  #defining color pallete
  colors <- cpt(pal = 'arendal_temperature')
  
  # Plot the raster objects 
  for (raster in rankmap_rasters) {
    plot(raster$raster, main = paste("Rank Map - Setup", variants[raster$id]), 
         col=colors)
  }
  
  # Reset the plotting layout
  par(mfrow = c(1, 1))
}